# Generated by Django 5.2.3 on 2025-06-27 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Applications',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('package_id', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField()),
                ('image_path', models.CharField(max_length=255)),
                ('rating', models.FloatField(default=0.0)),
            ],
        ),
    ]
