# Generated by Django 5.2.3 on 2025-07-04 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0002_rename_rating_applications_average_rating_apprating'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='average_rating',
            new_name='rating',
        ),
        migrations.DeleteModel(
            name='AppRating',
        ),
    ]
