# Generated by Django 5.2.3 on 2025-07-06 23:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0003_rename_average_rating_applications_rating_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='sentiment_negative',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='applications',
            name='sentiment_neutral',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='applications',
            name='sentiment_positive',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='applications',
            name='sentiment_score',
            field=models.FloatField(default=0.0),
        ),
    ]
