# Generated by Django 5.2.3 on 2025-07-12 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0004_applications_sentiment_negative_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='applications',
            name='appurl',
            field=models.URLField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='applications',
            name='rating_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='applications',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='applications',
            name='image_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
