# Generated by Django 5.2.3 on 2025-07-12 14:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('applications', '0006_comment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='applications',
            old_name='rating',
            new_name='app_quality_score',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sentiment_negative',
            new_name='avg_rating',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sentiment_neutral',
            new_name='negative_percent',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sentiment_positive',
            new_name='neutral_percent',
        ),
        migrations.RenameField(
            model_name='applications',
            old_name='sentiment_score',
            new_name='positive_percent',
        ),
        migrations.RemoveField(
            model_name='applications',
            name='rating_count',
        ),
    ]
